<?php

/**
 * ProfilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Profil');
    }
}